server:
  port: 18081
spring:
  application:
    name: dubbo-consumer
dubbo:
  application:
    name: dubbo-consumer
    logger: debug
  registry:
    protocol: zookeeper
    address: 192.168.0.9:2181
    timeout: 10000
  protocol:
    name: dubbo
    port: 28081